import io
from typing import Any

from models.schemas import KPIValue, BenchmarkComparison, AIInsight, ExecutiveStoryline, Industry


def export_to_pptx(request: Any) -> bytes:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Title slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = request.title or "InsightSynth AI Analysis Report"
    subtitle = slide.placeholders[1]
    subtitle.text = f"Industry: {request.industry.value}\nGenerated by InsightSynth AI"

    # Executive Summary slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Executive Summary"
    body = slide.placeholders[1]
    body.text = request.storyline.executive_summary

    # KPI Performance slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Key Performance Indicators"
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    for kpi in request.kpi_values:
        p = tf.add_paragraph()
        p.text = f"{kpi.kpi_name}: {kpi.value}{kpi.unit}"
        p.level = 0

    # Benchmark Comparison slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Benchmark Comparison"
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    for bc in request.benchmark_comparisons:
        p = tf.add_paragraph()
        p.text = f"{bc.kpi_name}: {bc.actual_value}{bc.unit} vs {bc.benchmark_value}{bc.unit} ({bc.performance_level})"
        p.level = 0

    # Insights slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Key Insights"
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    for insight in request.insights[:4]:
        p = tf.add_paragraph()
        p.text = insight.title
        p.level = 0
        p = tf.add_paragraph()
        p.text = insight.description[:150] + "..."
        p.level = 1

    # Recommendations slide
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    title.text = "Recommendations & Next Steps"
    body = slide.placeholders[1]
    tf = body.text_frame
    tf.clear()
    p = tf.add_paragraph()
    p.text = request.storyline.recommendation
    p.level = 0
    for step in request.storyline.next_steps:
        p = tf.add_paragraph()
        p.text = step
        p.level = 1

    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue()


def export_to_pdf(request: Any) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=30,
        textColor=HexColor("#1a365d"),
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=12,
        spaceBefore=20,
        textColor=HexColor("#2d3748"),
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        spaceAfter=8,
        leading=14,
    )

    elements = []

    # Title
    elements.append(Paragraph(request.title or "InsightSynth AI Analysis Report", title_style))
    elements.append(Paragraph(f"Industry: {request.industry.value}", body_style))
    elements.append(Spacer(1, 20))

    # Executive Summary
    elements.append(Paragraph("Executive Summary", heading_style))
    elements.append(Paragraph(request.storyline.executive_summary, body_style))
    elements.append(Spacer(1, 12))

    # KPI Table
    elements.append(Paragraph("Key Performance Indicators", heading_style))
    kpi_data = [["KPI", "Value", "Unit", "Trend"]]
    for kpi in request.kpi_values:
        kpi_data.append([kpi.kpi_name, str(kpi.value), kpi.unit, kpi.trend or "N/A"])

    if len(kpi_data) > 1:
        table = Table(kpi_data, colWidths=[2.5 * inch, 1.2 * inch, 1 * inch, 1.2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#2d3748")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, HexColor("#f7fafc")]),
        ]))
        elements.append(table)
    elements.append(Spacer(1, 12))

    # Benchmark Comparison Table
    elements.append(Paragraph("Benchmark Comparison", heading_style))
    bench_data = [["KPI", "Actual", "Benchmark", "Gap", "Performance"]]
    for bc in request.benchmark_comparisons:
        bench_data.append([
            bc.kpi_name,
            f"{bc.actual_value}{bc.unit}",
            f"{bc.benchmark_value}{bc.unit}",
            f"{bc.gap:+.1f}{bc.unit}",
            bc.performance_level,
        ])

    if len(bench_data) > 1:
        table = Table(bench_data, colWidths=[1.8 * inch, 1.1 * inch, 1.1 * inch, 1 * inch, 1.2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#2d3748")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, HexColor("#f7fafc")]),
        ]))
        elements.append(table)
    elements.append(Spacer(1, 12))

    # Insights
    elements.append(Paragraph("Key Insights", heading_style))
    for insight in request.insights:
        elements.append(Paragraph(f"<b>{insight.title}</b> [{insight.severity.upper()}]", body_style))
        elements.append(Paragraph(insight.description, body_style))
        elements.append(Paragraph(f"<i>Action: {insight.recommended_action}</i>", body_style))
        elements.append(Spacer(1, 8))

    # Recommendations
    elements.append(Paragraph("Recommendations", heading_style))
    elements.append(Paragraph(request.storyline.recommendation, body_style))
    elements.append(Spacer(1, 8))

    elements.append(Paragraph("Next Steps", heading_style))
    for step in request.storyline.next_steps:
        elements.append(Paragraph(f"  - {step}", body_style))

    doc.build(elements)
    return buffer.getvalue()


def export_to_xlsx(request: Any) -> bytes:
    import xlsxwriter

    buffer = io.BytesIO()
    workbook = xlsxwriter.Workbook(buffer)

    # Formats
    title_format = workbook.add_format({
        "bold": True, "font_size": 16, "font_color": "#1a365d",
    })
    header_format = workbook.add_format({
        "bold": True, "bg_color": "#2d3748", "font_color": "#ffffff",
        "border": 1, "text_wrap": True,
    })
    cell_format = workbook.add_format({"border": 1, "text_wrap": True, "valign": "top"})
    number_format = workbook.add_format({"border": 1, "num_format": "0.00"})

    # KPI Sheet
    ws = workbook.add_worksheet("KPIs")
    ws.write(0, 0, "Key Performance Indicators", title_format)
    headers = ["KPI Name", "Value", "Unit", "Trend", "Period"]
    for col, h in enumerate(headers):
        ws.write(2, col, h, header_format)
    for row, kpi in enumerate(request.kpi_values, start=3):
        ws.write(row, 0, kpi.kpi_name, cell_format)
        ws.write(row, 1, kpi.value, number_format)
        ws.write(row, 2, kpi.unit, cell_format)
        ws.write(row, 3, kpi.trend or "N/A", cell_format)
        ws.write(row, 4, kpi.period or "N/A", cell_format)
    ws.set_column(0, 0, 25)
    ws.set_column(1, 4, 15)

    # Benchmarks Sheet
    ws = workbook.add_worksheet("Benchmarks")
    ws.write(0, 0, "Benchmark Comparison", title_format)
    headers = ["KPI", "Actual", "Benchmark", "Top Quartile", "Gap", "Gap %", "Performance", "Source"]
    for col, h in enumerate(headers):
        ws.write(2, col, h, header_format)
    for row, bc in enumerate(request.benchmark_comparisons, start=3):
        ws.write(row, 0, bc.kpi_name, cell_format)
        ws.write(row, 1, bc.actual_value, number_format)
        ws.write(row, 2, bc.benchmark_value, number_format)
        ws.write(row, 3, bc.top_quartile, number_format)
        ws.write(row, 4, bc.gap, number_format)
        ws.write(row, 5, bc.gap_percentage, number_format)
        ws.write(row, 6, bc.performance_level, cell_format)
        ws.write(row, 7, bc.source, cell_format)
    ws.set_column(0, 0, 25)
    ws.set_column(1, 5, 12)
    ws.set_column(6, 6, 15)
    ws.set_column(7, 7, 40)

    # Insights Sheet
    ws = workbook.add_worksheet("Insights")
    ws.write(0, 0, "AI-Generated Insights", title_format)
    headers = ["Category", "Title", "Description", "Severity", "Confidence", "Recommended Action", "Impact Area"]
    for col, h in enumerate(headers):
        ws.write(2, col, h, header_format)
    for row, insight in enumerate(request.insights, start=3):
        ws.write(row, 0, insight.category, cell_format)
        ws.write(row, 1, insight.title, cell_format)
        ws.write(row, 2, insight.description, cell_format)
        ws.write(row, 3, insight.severity, cell_format)
        ws.write(row, 4, insight.confidence, number_format)
        ws.write(row, 5, insight.recommended_action, cell_format)
        ws.write(row, 6, insight.impact_area, cell_format)
    ws.set_column(0, 1, 25)
    ws.set_column(2, 2, 60)
    ws.set_column(3, 4, 12)
    ws.set_column(5, 5, 60)
    ws.set_column(6, 6, 25)

    # Executive Storyline Sheet
    ws = workbook.add_worksheet("Executive Storyline")
    ws.write(0, 0, "Executive Storyline", title_format)
    ws.set_column(0, 0, 20)
    ws.set_column(1, 1, 100)

    sections = [
        ("Executive Summary", request.storyline.executive_summary),
        ("Current Performance", request.storyline.current_performance),
        ("Key Insight", request.storyline.key_insight),
        ("Root Cause", request.storyline.root_cause),
        ("Business Impact", request.storyline.business_impact),
        ("Recommendation", request.storyline.recommendation),
        ("Next Steps", "\n".join(f"- {s}" for s in request.storyline.next_steps)),
    ]
    for row, (label, content) in enumerate(sections, start=2):
        ws.write(row, 0, label, header_format)
        ws.write(row, 1, content, cell_format)

    workbook.close()
    return buffer.getvalue()
